# -*- coding: utf-8 -*-
"""6단계 심화1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19G2Xv0D3JKNgExvFLY73sc4cjtUhQXGm
"""

#25083
print('         ,r\'\"7')
print('r`-_   ,\'  ,/')
print(' \. ". L_r\'')
print('   `~\\/')
print('      |')
print('      |')

#3003
a,b,c,d,e,f = map(int,input().split())
print(1-a,1-b,2-c,2-d,2-e,8-f)

#2444
n = int(input())
for i in range(1,n+1):
    print(' '*(n-i)+'*'*(2*i-1))
for i in range(n-1,0,-1):
    print(' '*(n-i)+'*'*(2*i-1))

#10988
s = input()
if s == s[::-1]:
  print(1)
else:
  print(0)

#1157
s = input()
s = s.upper()
s_list = list(set(s))
cnt = []
for i in s_list:
  count = s.count(i)
  cnt.append(count)

if cnt.count(max(cnt)) >= 2:
  print('?')
else:
  max_index = cnt.index(max(cnt))
  print(s_list[max_index])

#2941
croatia = ['c=','c-','dz=','d-','lj','nj','s=','z=']
word = input()
for i in croatia:
  word = word.replace(i,'*')
print(len(word))

#1316
n = int(input())
for i in range(n):
  word = input()
  for j in range(0,len(word)-1):
    if word[j] == word[j+1]:
      pass
    elif word[j] in word[j+1:]:
      n -= 1
      break
print(n)

#25206
subject = []
index = []
grade = []
for i in range(20):
  subject_value, index_value, grade_value = map(str,input().split())
  subject.append(subject_value)
  index.append(float(index_value))
  grade.append(grade_value)

sum_index = 0
sum_grade = 0
for i in range(20):
  if grade[i] == 'P':
    grade[i] = 0
    index[i] = 0
  elif grade[i] == 'A+':
    grade[i] = 4.5
  elif grade[i] == 'A0':
    grade[i] = 4.0
  elif grade[i] == 'B+':
    grade[i] = 3.5
  elif grade[i] == 'B0':
    grade[i] = 3.0
  elif grade[i] == 'C+':
    grade[i] = 2.5
  elif grade[i] == 'C0':
    grade[i] = 2.0
  elif grade[i] == 'D+':
    grade[i] = 1.5
  elif grade[i] == 'D0':
    grade[i] = 1
  elif grade[i] == 'F':
    grade[i] = 0
  sum_index += float(grade[i]) * index[i]
  sum_grade += index[i]

print(sum_index/sum_grade)