# -*- coding: utf-8 -*-
"""7단계_2차원_배열.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eaL_MSr7oIbiqHqVQ8e-nWNmNUuom5hy
"""

#2738
n,m = map(int,input().split())
a = []
b = []
for i in range(n):
    a.append(list(map(int,input().split())))
for i in range(n):
    b.append(list(map(int,input().split())))

for i in range(n):
  for j in range(m):
    print(a[i][j]+b[i][j],end=' ')
  print()

#2566
n = []
for i in range(9):
    n.append(list(map(int,input().split())))

max = 0
for i in range(9):
    for j in range(9):
        if max <= n[i][j]:
            max = n[i][j]
            x = i+1
            y = j+1
print(max)
print(f"{x} {y}")

#10798
n = []
for i in range(5):
    n.append(list(input()))

for i in range(15):
    for j in range(5):
        try:
            print(n[j][i],end='')
        except:
            continue

#2563
n = int(input())
paper = []
for i in range(100):
    paper.append([0 for i in range(100)])
for i in range(n):
    x,y = map(int,input().split())
    for j in range(x,x+10):
        for k in range(y,y+10):
            paper[j][k] = 1

count = 0
for i in range(100):
    for j in range(100):
        if paper[i][j] == 1:
            count += 11
print(count)