# -*- coding: utf-8 -*-
"""8단계 일반 수학 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/158d3B8CED5sGULlM8-C3iykZp9LwPC7Q
"""

#2745
n,m = map(str,input().split())
n = int(n,int(m))
print(n)

#11005
n,m = map(int, input().split())
a = []
while n > 0:
  a.append(n % m)
  n = n//m

for i in range(len(a)):
  if a[i] >= 10:
    a[i] = chr(a[i]+55)

a = a[::-1]
for i in a:
  print(i,end='')

#2720
n = int(input())
for i in range(n):
  a = int(input())
  q = a//25
  a = a%25
  d = a//10
  a = a%10
  n = a//5
  p = a%5
  print(q,d,n,p)

#2903
n = int(input())
m = 3
for i in range(n-1):
  m = m*2-1
print(m**2)

#2292
N = int(input())
i = 1
while N > 1:
  N = N-6*i
  i += 1
print(i)

#1193
x = int(input())
line = 1
while x > line:
  x -= line
  line += 1
if line % 2 == 0:
  a = x
  b = line - x + 1
else:
  a = line - x + 1
  b = x
print(f'{a}/{b}')

#2869
a,b,v = map(int,input().split())
k = (v-b)/(a-b)
if k == int(k):
  print(int(k))
else:
  print(int(k)+1)

