# -*- coding: utf-8 -*-
"""10단계 기하: 직사각형과 삼각형.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W33vUCV8Gff3DT9zuvprybqDZJBdcEZN
"""

#27323
a = int(input())
b = int(input())

print(a*b)

#1085
x,y,w,h = map(int,input().split())
print(min(x,y,w-x,h-y))

#3009
n, m = [], []
for i in range(3):
    a, b = map(int, input().split())
    n.append(a)
    m.append(b)
for i in n:
    if n.count(i) == 1:
        x = i
for i in m:
    if m.count(i) == 1:
        y = i
print(x, y)

#15894
a = int(input())
print(a*4)

#9063
n = int(input())
x, y = [], []
for i in range(n):
    a, b = map(int, input().split())
    x.append(a)
    y.append(b)
print((max(x)-min(x))*(max(y)-min(y)))

#10101
a = int(input())
b = int(input())
c = int(input())

if a+b+c != 180:
  print('Error')
elif a == b == c == 60:
    print('Equilateral')
elif a == b or b == c or c == a:
    print('Isosceles')
else:
    print('Scalene')

#5073
while True:
  a, b, c = map(int, input().split())
  if a == b == c == 0:
    break
  if a >= b + c or b >= a + c or c >= a + b:
    print('Invalid')
    continue
  if a == b == c:
    print('Equilateral')
  elif a == b or b == c or c == a:
    print('Isosceles')
  else:
    print('Scalene')

#14215
a, b, c = map(int, input().split())
if a+b > c and b+c > a and c+a > b:
  print(a+b+c)
else:
  if max(a,b,c) == a:
    print(2*(b+c)-1)
  elif max(a,b,c) == b:
    print(2*(a+c)-1)
  else:
    print(2*(a+b)-1)

