# -*- coding: utf-8 -*-
"""입출력과 사칙연산

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ABrxhOPrf0gfgyzPtMVXTxNtyoMqz8kn
"""

#2557
print("Hello World!")

#1000
A, B = map(int, input().split())
print(A + B)

#1001
A, B = map(int, input().split())
print(A - B)

#10998
A, B = map(int, input().split())
print(A * B)

#1008
A, B = map(int, input().split())
print(A / B)

#10869
A, B = map(int, input().split())
print(A + B)
print(A - B)
print(A * B)
print(A // B)
print(A % B)

#10926
name = input("")
print(name + "??!")

#18108
year = int(input(""))
print(year - 543)

#10430
A,B,C = map(int, input().split())
print((A+B)%C)
print(((A%C) + (B%C))%C)
print((A*B)%C)
print(((A%C) * (B%C))%C)

#2588
A = int(input(""))
B = input("")
print(A * int(B[2]))
print(A * int(B[1]))
print(A * int(B[0]))
print(A * int(B))

#11382
A, B, C = map(int, input().split())
print(A + B + C)

#10171
print("\    /\\")
print(" )  ( ')")
print("(  /  )")
print(" \(__)|")

#10172
print("|\_/|")
print("|q p|   /}")
print("( 0 )\"\"\"\\")
print("|\"^\"`    |")
print("||_/=\\\__|")