# -*- coding: utf-8 -*-
"""2단계_조건문.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LCf1vmzoImydERMyFZdM091kuVMHklbF
"""

#1330
a,b=map(int,input().split())
if a>b:
    print('>')
elif a<b:
    print('<')
else:
    print('==')

#9498
a = int(input())
if a>=90:
    print('A')
elif a>=80:
    print('B')
elif a>=70:
    print('C')
elif a>=60:
    print('D')
else:
    print('F')

#2753
a=int(input())
if a%4==0 and a%100!=0 or a%400==0:
    print('1')
else:
    print('0')

#14681
a=int(input())
b=int(input())
if a>0 and b>0:
    print('1')
elif a<0 and b>0:
    print('2')
elif a<0 and b<0:
    print('3')
else:
    print('4')

#2884
h, m = map(int,input().split())
if m>44:
    print(h,m-45)
elif m<45 and h>0:
    print(h-1,m+15)
else:
    print(23,m+15)

#2525
a,b=map(int,input().split())
c=int(input())
a+=c//60
b+=c%60
if b>=60:
    a+=1
    b-=60
if a>=24:
    a-=24
print(a,b)

#2480
a,b,c=map(int,input().split())
if a==b==c:
  print(10000+a*1000)
elif a==b or a==c:
  print(1000+a*100)
elif b==c:
  print(1000+b*100)
else:
  print(max(a,b,c)*100)

