# -*- coding: utf-8 -*-
"""3단계 반복문.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XhlKCZsyGvlfgrVKgyXHPKoHODyjosAj
"""

#2739
n = int(input())
for i in range(1,10):
    print(n, '*', i, '=', int(n)*i)

#10950
t = int(input())
for i in range(t):
    a, b = map(int, input().split())
    print(a+b)

#8393
n = int(input())
sum = 0
for i in range(1, n+1):
  sum += i
print(sum)

#25304
m = int(input())
n = int(input())
sum = 0
for i in range(n):
  a, b = map(int, input().split())
  sum += a*b
if sum == m:
  print('Yes')
else:
  print('No')

#25314
n = int(input())
for i in range(n//4):
  print('long', end = ' ')
print('int')

#15552
import sys
t = int(sys.stdin.readline())
for i in range(t):
  a, b = map(int, sys.stdin.readline().split())
  print(a+b)

#11021
t = int(input())
for i in range(t):
  a, b = map(int, input().split())
  print('Case #' + str(i+1) + ':', a+b)

#11022
t = int(input())
for i in range(t):
  a, b = map(int, input().split())
  print('Case #' + str(i+1) + ':', a, '+', b, '=', a+b)

#2438
n = int(input())
for i in range(1, n+1):
  print('*'*i)

#2439
n = int(input())
for i in range(1, n+1):
  print(' '*(n-i) + '*'*i)

#10952
while True:
  a, b = map(int, input().split())
  if a == 0 and b == 0:
    break
  print(a+b)

#10951
while True:
  try:
    a, b = map(int, input().split())
    print(a+b)
  except:
    break