# -*- coding: utf-8 -*-
"""4단계 1차원 배열.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G2vnpAws5Qn471SnP2Y_Nzlen0BJqOSv
"""

#10807
n = int(input())
arr = list(map(int, input().split()))
v = int(input())
cnt = 0
for i in arr:
    if i == v:
        cnt += 1
print(cnt)

#10871
n, x = map(int, input().split())
arr = list(map(int, input().split()))
for i in arr:
    if i < x:
        print(i, end = ' ')

#10818
n = int(input())
arr = list(map(int, input().split()))
print(min(arr), max(arr))

#2562
arr = []
for i in range(9):
  arr.append(int(input()))
print(max(arr))
print(arr.index(max(arr))+1)

#10810
n, m = map(int, input().split())
arr = list(range(n))
for x in arr:
  arr[x] = 0
for i in range(m):
  a,b,c = map(int, input().split())
  for j in range(a-1,b):
    arr[j] = c

for t in range(len(arr)):
  print(arr[t], end = " ")

#10813
n, m = map(int, input().split())
arr = list(range(n))
for x in arr:
  arr[x] = x+1
for i in range(m):
  a,b = map(int, input().split())
  arr[a-1], arr[b-1] = arr[b-1], arr[a-1]
for t in range(len(arr)):
  print(arr[t], end = " ")

#5597
arr = list(range(1,31))
for i in range(28):
  a = int(input())
  arr.remove(a)
print(min(arr))
print(max(arr))

#3052
arr = []
for i in range(10):
  a = int(input())
  arr.append(a%42)
arr_set = set(arr)
print(len(arr_set))

#10811
n, m = map(int, input().split())
arr = list(range(1,n+1))
for i in range(m):
  a,b = map(int, input().split())
  arr[a-1:b] = arr[a-1:b][::-1]
for t in range(len(arr)):
  print(arr[t], end = " ")

#1546
n = int(input())
arr = list(map(int, input().split()))
arr_max = max(arr)
for i in range(n):
  arr[i] = arr[i]/arr_max*100
sum = 0
for i in range(n):
  sum += arr[i]
print(sum/n)