# -*- coding: utf-8 -*-
"""9단계 약수, 배수와 소수.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cGopZfEqeAuZHlJhX7znA6HEeOirRdn2
"""

#5086
try:
    while True:
        a, b = map(int, input().split())
        if a == 0 and b == 0:
            break
        if b % a == 0:
            print('factor')
            continue
        if a % b == 0:
            print('multiple')
            continue
        print('neither')
except:
    pass

#2501
n, k = map(int, input().split())
cnt = []
for i in range(1, n+1):
    if n % i == 0:
        cnt.append(i)
    if cnt == n:
        break
if len(cnt) >= k:
    print(cnt[k-1])
else:
    print(0)

#9506
while True:
    n = int(input())
    if n == -1:
        break
    cnt = []
    for i in range(1, n):
        if n % i == 0:
            cnt.append(i)
    if n == sum(cnt):
        print(f'{n} = {" + ".join(map(str, cnt))}')
    else:
        print(f'{n} is NOT perfect.')

#1978
n = int(input())
a = list(map(int, input().split()))
cnt = 0
for i in a:
    if i == 1:
        continue
    for j in range(2, i):
        if i % j == 0:
            break
    else:
        cnt += 1
print(cnt)

#2581
m = int(input())
n = int(input())
cnt = []
for i in range(m, n+1):
    if i == 1:
        continue
    for j in range(2, i):
        if i % j == 0:
            break
    else:
        cnt.append(i)
if len(cnt) == 0:
    print(-1)
else:
    print(sum(cnt))
    print(min(cnt))

#11653
n = int(input())
for i in range(2, n+1):
    while n % i == 0:
        print(i)
        n //= i

